name: eh_redux
description: EH Redux
publish_to: "none"
version: 0.6.4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.6.1
  built_collection: ^5.1.0
  built_value: ^8.1.1
  cached_network_image: ^3.1.0
  collection: ^1.15.0
  device_info: ^2.0.2
  enum_to_string: ^2.0.1
  filesize: ^2.0.1
  firebase_analytics: ^8.2.0
  firebase_core: ^1.4.0
  firebase_crashlytics: ^2.1.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.1.2
  flutter_local_notifications: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.3
  flutter_mobx: ^2.0.1
  flutter_secure_storage: ^4.2.1
  flutter_typeahead: ^3.2.0
  freezed_annotation: ^0.14.2
  functional_widget_annotation: ^0.9.0
  html: ^0.15.0
  html_unescape: ^2.0.0
  http: ^0.13.3
  intl: ^0.17.0
  json_annotation: ^4.0.1
  logging: ^1.0.1
  meta: ^1.3.0
  mobx: ^2.0.3
  moor: ^4.4.1
  octo_image: ^1.0.0+1
  package_info: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.2
  photo_view: ^0.12.0
  preload_page_view: ^0.1.6
  provider: ^5.0.0
  rxdart: ^0.27.1
  share: ^2.0.4
  shared_preferences: ^2.0.6
  sqlite3_flutter_libs: ^0.5.0
  streaming_shared_preferences: ^2.0.0
  url_launcher: ^6.0.9
  webview_flutter: ^2.0.10
  workmanager: ^0.4.1

dev_dependencies:
  build_runner: ^2.0.6
  built_value_generator: ^8.1.1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  functional_widget: ^0.9.0+2
  json_serializable: ^4.1.4
  json_serializable_immutable_collections: ^0.8.0
  lint: ^1.5.3
  matcher: ^0.12.10
  mobx_codegen: ^2.0.2
  mockito: ^5.0.13
  moor_generator: ^4.4.1

flutter:
  uses-material-design: true
  generate: true
